blank_issues_enabled: false
contact_links:
    - name: Help
      url: https://github.com/Paraliyzedevo/SonataOverlay/discussions/categories/q-a
      about: Is the overlay not working or performing as you'd expect? Not sure it's a bug? Check the Q&A section!
    - name: Suggestions or feature request
      url: https://github.com/Paraliyzedevo/SonataOverlay/discussions/categories/ideas
      about: Got something you think should change or be added? Search for or start a new discussion!
    - name: More places to get help
      url: https://paraliyzed.net
      about: If you can't seem to get into contact with Paraliyzed_evo here, use my website to find more places to get into contact with me.